# Generated by Django 4.2.13 on 2026-06-21 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('payment_received', 'Payment Received'), ('car_available', 'Car Available'), ('review_received', 'Review Received'), ('company_approved', 'Company Approved'), ('company_suspended', 'Company Suspended'), ('wallet_credit', 'Wallet Credit'), ('wallet_debit', 'Wallet Debit'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
