# Generated by Django 4.2.13 on 2026-06-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='wallet_belongs_to_one_owner',
        ),
    ]
