# Generated by Django 4.2.13 on 2026-06-21 08:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(choices=[('Economy', 'Economy'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Luxury', 'Luxury'), ('Sports', 'Sports'), ('Van', 'Van'), ('Truck', 'Truck'), ('Electric', 'Electric'), ('4x4', '4x4')], default='Economy', max_length=20)),
                ('transmission', models.CharField(choices=[('Auto', 'Automatic'), ('Manual', 'Manual')], default='Auto', max_length=10)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=10)),
                ('seats', models.PositiveSmallIntegerField(default=5)),
                ('doors', models.PositiveSmallIntegerField(default=4)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_gps', models.BooleanField(default=False)),
                ('has_bluetooth', models.BooleanField(default=False)),
                ('has_usb', models.BooleanField(default=False)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=15)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'car_features',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'car_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cars.car')),
            ],
            options={
                'db_table': 'favorite_cars',
            },
        ),
    ]
