# Generated by Django 4.2.13 on 2026-06-21 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car'),
        ),
        migrations.AddField(
            model_name='carfeature',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car'),
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecar',
            unique_together={('user', 'car')},
        ),
        migrations.AlterUniqueTogether(
            name='carfeature',
            unique_together={('car', 'label')},
        ),
    ]
